export const longGun = ['xxxxxxxx xxxxx   xxx      xxxxxxx xxxxx'];

export const gosperGliderGun = [
  '                        x           ',
  '                      x x           ',
  '            xx      xx            xx',
  '           x   x    xx            xx',
  'xx        x     x   xx              ',
  'xx        x   x xx    x x           ',
  '          x     x       x           ',
  '           x   x                    ',
  '            xx                      ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
];

export const blinkBloom = [
  '  xxx   xxx  ',
  '             ',
  'x    x x    x',
  'x    x x    x',
  'x    x x    x',
  '  xxx   xxx  ',
  '             ',
  '  xxx   xxx  ',
  'x    x x    x',
  'x    x x    x',
  'x    x x    x',
  '             ',
  '  xxx   xxx  ',
];
