export const longGun = ['xxxxxxxx xxxxx   xxx      xxxxxxx xxxxx'];

export const gosperGliderGun = [
  '                        x           ',
  '                      x x           ',
  '            xx      xx            xx',
  '           x   x    xx            xx',
  'xx        x     x   xx              ',
  'xx        x   x xx    x x           ',
  '          x     x       x           ',
  '           x   x                    ',
  '            xx                      ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
  '                                    ',
];

export const pulsar = [
  '  xxx   xxx  ',
  '             ',
  'x    x x    x',
  'x    x x    x',
  'x    x x    x',
  '  xxx   xxx  ',
  '             ',
  '  xxx   xxx  ',
  'x    x x    x',
  'x    x x    x',
  'x    x x    x',
  '             ',
  '  xxx   xxx  ',
];

export const spaceship = [
  '                                                     x ',
  '                                    x               x x',
  '                          x x      x     xx        x   ',
  '                          x    x    x xxxxxx    xx     ',
  '                          x xxxxxxxx          x  x xxx ',
  '                             x     x       xxxx    xxx ',
  '                        xx                 xxx x       ',
  '                     x  xx       xx        xx          ',
  '                     x  x                              ',
  '                    x                                  ',
  '                     x  x                              ',
  '                     x  xx       xx        xx          ',
  '                        xx                 xxx x       ',
  '                             x     x       xxxx    xxx ',
  '                          x xxxxxxxx          x  x xxx ',
  '                          x    x    x xxxxxx    xx     ',
  '                          x x      x     xx        x   ',
  '                                    x               x x',
  '                                                     x ',
];

export const acorn = [' x     ', '   x   ', 'xx  xxx'];

export const simkinGliderGun = [
  'xx     xx                        ',
  'xx     xx                        ',
  '                                 ',
  '    xx                           ',
  '    xx                           ',
  '                                 ',
  '                                 ',
  '                                 ',
  '                                 ',
  '                      xx xx      ',
  '                     x     x     ',
  '                     x      x  xx',
  '                     xxx   x   xx',
  '                          x      ',
  '                                 ',
  '                                 ',
  '                                 ',
  '                    xx           ',
  '                    x            ',
  '                     xxx         ',
  '                       x         ',
];

export const longFrame = [
  'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxx                                                                                                                                                          xxx',
  'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
];
